#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 24 18:50:36 2021

@author: federico
"""


def get_symbols_string_STOXXE600():
    symbols = """NESN.SW ROG.SW NOVN.SW ASML.AS MC.PA AZN.L LIN.DE SAP.DE SAN.PA NOVO-B.CO
           SIE.DE FP.PA HSBA.L GSK.L ALV.DE DGE.L OR.PA UNA.AS BATS.L AI.PA
           SU.PA IBE.MC ENEL.MI RIO.L RB.L BP.L RDSA.L BAS.DE ADS.DE STLA.PA
           AIR.PA DG.PA BNP.PA DTE.DE ABI.BR ZURN.SW BAYN.DE KER.PA DAI.DE ABBN.SW
           ADYEN.AS SAF.PA UBSG.SW PHIA.AS REL.L LONN.SW PRX.AS SAN.MC DPW.DE BHP.L
           CS.PA NG.L PRU.L CFR.SW EL.PA BN.PA VOD.L IFX.DE MUV2.DE ISP.MI
           RI.PA EXPN.L ITX.MC SIKA.SW ERIC-B.ST VOLV-B.ST VWS.CO KNEBV.HE RMS.PA LSEG.L
           INGA.AS AAL.L CPG.L VNA.DE DSV.CO VOW.DE CRG.IR GIVN.SW ALC.SW ATCO-A.ST
           INVE-B.ST AMS.MC ORSTED.CO LLOY.L AD.AS NDA-SE.ST BARC.L DB1.DE DSM.AS TSCO.L
           CSGN.SW GLEN.L NESTE.HE FLTR.IR BMW.DE ENGI.PA HEIA.AS RWE.DE VIV.PA LHN.SW
           ASSA-B.ST SREN.SW SGO.PA DSY.PA EOAN.DE RACE.MI FERG.L BBVA.MC GMAB.CO WKL.AS
           ORA.PA SAND.ST CAP.PA ENI.MI SAMPO.HE LR.PA HEXA-B.ST STM.MI GEBN.SW DBK.DE
           ML.PA UCG.MI CLNX.MC KRZ.IR NOKIA.HE G.MI TEF.MC ESSITY-B.ST BA.L MRK.DE
           HEN.DE AKZA.AS AHT.L PGHN.SW SSE.L TEP.PA SN.L LGEN.L FRE.DE OCDO.L
           FME.DE SGSN.SW COLO-B.CO SWED-A.ST DHER.DE UPM.HE SEB-A.ST IMB.L KBC.BR AV.L
           DWNI.DE GLE.PA FCA.MI ZAL.DE SY1.DE CARL-B.CO DNB.OL EQNR.OL HM-B.ST SHB-A.ST
           FER.MC STAN.L EDP.LS SOON.SW UCB.BR SRT3.DE KRX.IR BT-A.L SGRO.L EQT.ST
           EDEN.PA CON.DE REP.MC LOGN.SW III.L STMN.SW WLN.PA SLHN.SW ACA.PA SCMN.SW
           RTO.L NN.AS ITRK.L AENA.MC TKWY.AS MTX.F SWMA.ST HLMA.L NZYM-B.CO WPP.L
           UG.PA BAER.SW ARGX.BR NXT.L VIE.PA EN.PA CRDA.L BEI.DE IHG.L ENR.DE
           KNIN.SW INF.L PSN.L MT.AS SPX.L SRG.MI KINV-B.ST SCHN.SW BNZL.L DANSKE.CO
           HNR1.DE QIA.DE BNR.DE TEL.OL EPI-A.ST CHR.CO MAERSK-B.CO TRN.MI MNDI.L ERF.PA
           TELIA.ST KPN.AS HEI.DE ALO.PA SGE.L GBLB.BR STERV.HE RY4C.IR ABF.L SKA-B.ST
           PAH3.DE EVO.ST FGR.PA CA.PA HEIO.AS PUB.PA LEG.DE LISN.SW ADEN.SW NIBE-B.ST
           CNHI.MI SK3.IR GN.CO MONC.MI ATL.MI MRO.L PNDORA.CO HO.PA SKF-B.ST GRF.MC
           FORTUM.HE ELE.MC 1COV.DE RSA.L MOWI.OL UBI.PA ADM.L FBK.MI NWG.L ING.PA
           BRBY.L CABK.MC AGS.BR BOL.ST URW.AS SCA-B.ST DIM.PA FR.PA REE.MC TEMN.SW
           UMI.BR BDEV.L UU.L SMIN.L ELISA.HE SVT.L G24.DE PUM.DE SLA.L PRY.MI
           STJ.L KGF.L RMV.L AKE.PA EBS.VI GVC.L SOLB.BR BKG.L BALN.SW RAND.AS
           DCC.L ATO.PA POLY.L SEV.PA GET.PA NTGY.MC AT1.DE HFG.DE ACS.MC ORK.OL
           SW.PA BVI.PA AUTO.L UHR.SW EXO.MI WTB.L ASM.AS GFC.PA EMSN.SW TW.L
           SPSN.SW PHNX.L SHL.DE SGRE.MC KESKOA.HE KBX.DE RNO.PA ALFA.ST HL.L YAR.OL
           ORP.PA EDF.PA BIM.PA 7CD.SG JMAT.L VIFN.SW IMCD.AS BARN.SW TEL2-B.ST AGN.AS
           NEXI.MI MGCI.L LAND.L AC.PA SIGN.SW AMS.SW PSON.L ICP.L SCR.PA PNN.L
           PSPN.SW CBK.DE CAST.ST ANTO.L CCH.L HIK.L P9O.MU SMDS.L WEIR.L ENX.PA
           ENG.MC MOCORP.HE BLND.L KGX.DE SECU-B.ST MB.MI TMV.DE BME.L EVK.DE ASRNL.AS
           BALD-B.ST ELUX-B.ST AMBU-B.CO MRW.L GLPG.AS REC.MI VACN.SW CPR.MI SDR.L HUH1V.HE
           INDU-A.ST DLG.L GALP.LS AMP.MI LIGHT.AS DIA.MI HWDN.L LXS.DE SIM.CO G1A.DE
           TREL-B.ST AFX.DE CLN.SW ORNBV.HE BC8.DE ABN.AS KGHA.F HSX.L EKTA-B.ST AMUN.PA
           FDJ.PA SBRY.L BWY.L DPH.L HSV.L NHY.OL 0QP4.IL RBREW.CO COV.PA TOM.OL
           ECM.L UTG.L INDT.ST JD.L SOF.BR WRT1V.HE GETI-B.ST IAG.L LI.PA DLN.L
           SK.PA LUNE.ST WDP.BR PST.MI GFS.L ICA.ST TECN.SW TEG.DE OMV.VI GAW.L
           SINCH.ST FABG.ST TYRES.HE CTEC.L SXS.L ITV.L TATE.L BEAN.SW VER.VI HUSQ-B.ST
           TPK.L IMI.L MGGT.L RAA.DE COFB.BR NEM.DE RHM.DE JMT.LS KOJAMO.HE GJF.OL
           RUI.PA TIT.MI HOLM-B.ST UTDI.DE PKY1.F AVST.L AALB.AS SWEC-B.ST WMH.L RCO.PA
           INW.MI FPE3.DE IGG.L LUND-B.ST CMBN.SW ADP.PA 7PZ.F GNS.L ROCK-B.CO AED.BR
           ADE.OL AAK.ST CNP.PA BOL.PA BBOX.L IPN.PA SESG.PA NETC.CO TRYG.CO LIFCO-B.ST
           LATO-B.ST VALMT.HE EVT.DE ELI.BR SOI.PA AVV.L IP.MI SOBI.ST VPK.AS ROR.L
           CNA.L DPLM.L MOR.DE ILD.PA LHA.DE BP1.F VOE.VI GALE.SW HELN.SW FTI.PA
           IWG.L WIE.VI EO.PA BAKKA.OL SBB-B.ST THULE.ST BESI.AS BAMI.MI ATC.AS FHZN.SW
           ALLN.SW INCH.L SCHA.OL DOM.ST EVD.DE ACKB.BR PROX.BR WALL-B.ST BKT.MC MRL.MC
           MKS.L ADDT-B.ST RXL.PA RMG.L TEN.MI STB.OL BG.VI IG.MI GXI.DE ATE.PA
           SALM.OL BILL.ST COLR.BR BCVN.SW DEMANT.CO MF.PA WIHL.ST BVIC.L EDPR.LS NEL.OL
           EVR.L UN01.DE HAS.L QLT.L RF.PA DLG.DE DLG.F ANDR.VI CRBN.AS ISS.CO BEZ.L
           ELIS.PA BIRG.IR HER.MI PSM.DE RR.L AOX.DE IDIA.SW SBMO.AS HPOL-B.ST LMP.L
           FRES.L KN.PA AGR.L 1RY.F VIS.MC CBG.L LDO.MI FNTN.DE AF-B.ST PHP.L
           TRN.L COL.MC CWK.L SRAIL.SW GYC.DE ENTRA.OL GRI.L O2D.DE ANA.MC RBI.VI
           AM.PA AXFO.ST VAR1.DE SPIE.PA JDEP.AS TKA.DE ASHM.L CCL.L ADJ.DE
           SWON.SW EMG.L ICAD.PA UDG.L VCT.L A2A.MI BEIJ-B.ST GL9.IR SAB.MC SAAB-B.ST
           SIG.L SOP.PA AKERBP.OL AKRBP.OL TOP.CO MONY.L COK.DE LUN.CO CEY.L NETW.L TCAP.L
           SRCG.SW 5Y2.F MNG.L ENT.L"""
    return symbols


def get_symbols_string_SP500():
    symbols = """A AAL AAP AAPL ABBV ABC ABMD ABT ACN ADBE ADI ADM ADP ADS
                ADSK AEE AEP AES AFL AGN AIG AIV AIZ AJG AKAM ALB ALGN ALK
                ALL ALLE ALXN AMAT AMCR AMD AME AMGN AMP AMT AMZN ANET ANSS
                ANTM AON AOS APA APD APH APTV ARE ATO ATVI AVB AVGO AVY AWK
                AXP AZO BA BAC BAX BBY BDX BEN BF-B BIIB BK BKNG BKR BLK BLL
                BMY BR BRK-B BSX BWA BXP C CAG CAH CARR CAT CB CBOE CBRE CCI
                CCL CDNS CDW CE CERN CF CFG CHD CHRW CHTR CI CINF CL CLX CMA
                CMCSA CME CMG CMI CMS CNC CNP COF COG COO COP COST COTY CPB
                CPRI CPRT CRM CSCO CSX CTAS CTSH CTVA CTXS CVS CVX CXO D DAL
                DD DE DFS DG DGX DHI DHR DIS DISCA DISCK DISH DLR DLTR DOV DOW
                DRE DRI DTE DUK DVA DVN DXC DXCM EA EBAY ECL ED EFX EIX EL EMN EMR
                EOG EQIX EQR ES ESS ETFC ETN ETR EVRG EW EXC EXPD EXPE EXR F
                FANG FAST FB FBHS FCX FDX FE FFIV FIS FISV FITB FLIR FLS FLT
                FMC FOX FOXA FRC FRT FTI FTNT FTV GD GE GILD GIS GL GLW GM
                GOOG GOOGL GPC GPN GPS GRMN GS GWW HAL HAS HBAN HBI HCA HD
                HES HFC HIG HII HLT HOG HOLX HON HP HPE HPQ HRB HRL HSIC HST
                HSY HUM HWM IBM ICE IDXX IEX IFF ILMN INCY INFO INTC INTU IP
                IPG IPGP IQV IR IRM ISRG IT ITW IVZ J JBHT JCI JKHY JNJ JNPR
                JPM JWN K KEY KEYS KHC KIM KLAC KMB KMI KMX KO KR KSS KSU L
                LB LDOS LEG LEN LH LHX LIN LKQ LLY LMT LNC LNT LOW LRCX LUV
                LVS LW LYB LYV MA MAA MAR MAS MCD MCHP MCK MCO MDLZ MDT MET
                MGM MHK MKC MKTX MLM MMC MMM MNST MO MOS MPC MRK MRO MS MSCI
                MSFT MSI MTB MTD MU MXIM MYL NBL NCLH NDAQ NEE NEM NFLX NI
                NKE NLOK NLSN NOC NOV NOW NRG NSC NTAP NTRS NUE NVDA NVR NWL
                NWS NWSA O ODFL OKE OMC ORCL ORLY OTIS OXY PAYC PAYX PBCT PCAR
                PEAK PEG PEP PFE PFG PG PGR PH PHM PKG PKI PLD PM PNC PNR PNW POOL
                PPG PPL PRGO PRU PSA PSX PVH PWR PXD PYPL QCOM QRVO RCL RE REG
                REGN RF RHI RJF RL RMD ROK ROL ROP ROST RSG RTN SBAC SBUX SCHW
                SEE SHW SIVB SJM SLB SLG SNA SNPS SO SPG SPGI SRE STE STT STX
                STZ SWK SWKS SYF SYK SYY T TAP TDG TEL TFC TFX TGT TIF TJX TMO
                TMUS TPR TROW TRV TSCO TSN TT TTWO TWTR TXN TXT UA UAA UAL UDR
                UHS ULTA UNH UNM UNP UPS URI USB V VAR VFC VIAC VLO VMC VNO
                VRSK VRSN VRTX VTR VZ WAB WAT WBA WDC WEC WELL WFC WHR WLTW
                WM WMB WMT WRB WRK WU WY WYNN XEL XLNX XOM XRAY XRX XYL YUM
                ZBH ZBRA ZION ZTS"""
    return symbols
